version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3366/kittens_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  db:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kittens_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3366:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
